//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Catalogo
    {
        public string IdCatalogo { get; set; }
        public string nom_catalogo { get; set; }
        public string IdTipoCatalogo { get; set; }
        public string estado { get; set; }
    
        public virtual mail_Catalogo_Tipo mail_Catalogo_Tipo { get; set; }
    }
}
