//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Mensaje_Archi_Adjunto
    {
        public decimal IdMensaje { get; set; }
        public int Secuencia { get; set; }
        public byte[] Archivo_adjunto { get; set; }
        public string descripcion_archi { get; set; }
        public string extencion { get; set; }
        public string IdComprobante { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        public virtual mail_Mensaje mail_Mensaje { get; set; }
    }
}
