//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Parametro
    {
        public string IdParametro { get; set; }
        public int valor_min_envi_recep_aut { get; set; }
        public bool envio_recep_aut_salir { get; set; }
        public Nullable<bool> enviar_solo_pdf_ride { get; set; }
        public Nullable<bool> enviar_solo_xml_ride { get; set; }
    }
}
