//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Catalogo_Tipo
    {
        public mail_Catalogo_Tipo()
        {
            this.mail_Catalogo = new HashSet<mail_Catalogo>();
        }
    
        public string IdTipoCatalogo { get; set; }
        public string nom_TipoCatalogo { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<mail_Catalogo> mail_Catalogo { get; set; }
    }
}
