//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_menu
    {
        public seg_menu()
        {
            this.seg_menu1 = new HashSet<seg_menu>();
            this.seg_menu_x_tb_empresa = new HashSet<seg_menu_x_tb_empresa>();
            this.seg_menu_x_tb_empresa_x_seg_usuario = new HashSet<seg_menu_x_tb_empresa_x_seg_usuario>();
        }
    
        public int IdMenu { get; set; }
        public Nullable<int> IdMenu_padre { get; set; }
        public string me_nombre { get; set; }
        public bool me_es_menu { get; set; }
        public string me_nom_formulario { get; set; }
        public string me_nom_assembly { get; set; }
        public int me_nivel { get; set; }
        public bool me_estado { get; set; }
    
        public virtual ICollection<seg_menu> seg_menu1 { get; set; }
        public virtual seg_menu seg_menu2 { get; set; }
        public virtual ICollection<seg_menu_x_tb_empresa> seg_menu_x_tb_empresa { get; set; }
        public virtual ICollection<seg_menu_x_tb_empresa_x_seg_usuario> seg_menu_x_tb_empresa_x_seg_usuario { get; set; }
    }
}
