//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_usuario
    {
        public seg_usuario()
        {
            this.seg_menu_x_tb_empresa_x_seg_usuario = new HashSet<seg_menu_x_tb_empresa_x_seg_usuario>();
            this.seg_usuario_x_tb_empresa = new HashSet<seg_usuario_x_tb_empresa>();
        }
    
        public string IdUsuario { get; set; }
        public string us_contrasenia { get; set; }
        public string us_nombre { get; set; }
        public bool estado { get; set; }
    
        public virtual ICollection<seg_menu_x_tb_empresa_x_seg_usuario> seg_menu_x_tb_empresa_x_seg_usuario { get; set; }
        public virtual ICollection<seg_usuario_x_tb_empresa> seg_usuario_x_tb_empresa { get; set; }
    }
}
