//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_menu_x_tb_empresa
    {
        public int IdEmpresa { get; set; }
        public int IdMenu { get; set; }
        public bool estado { get; set; }
    
        public virtual seg_menu seg_menu { get; set; }
        public virtual tb_Empresa tb_Empresa { get; set; }
    }
}
