//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Catalogo
    {
        public tb_Catalogo()
        {
            this.tb_Comprobante = new HashSet<tb_Comprobante>();
        }
    
        public string IdCatalogo { get; set; }
        public int IdTIpoCatalogo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual tb_Catalogo_tipo tb_Catalogo_tipo { get; set; }
        public virtual ICollection<tb_Comprobante> tb_Comprobante { get; set; }
    }
}
