//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Catalogo_tipo
    {
        public tb_Catalogo_tipo()
        {
            this.tb_Catalogo = new HashSet<tb_Catalogo>();
        }
    
        public int IdTipoCatalogo { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<tb_Catalogo> tb_Catalogo { get; set; }
    }
}
