//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_comprobantes_No_Generados
    {
        public string id_Comprobante { get; set; }
        public string Nom_vista { get; set; }
        public string Mensaje_Error { get; set; }
        public System.DateTime Fecha_Carga { get; set; }
    }
}
