//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Clave_Conting
    {
        public int IdEmpresa { get; set; }
        public decimal IdClave { get; set; }
        public bool Usado { get; set; }
        public System.DateTime Fecha_Trans { get; set; }
        public string ClaveContingencia { get; set; }
        public System.DateTime Fecha_Importacion { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdAmbiente { get; set; }
    
        public virtual tb_Empresa tb_Empresa { get; set; }
    }
}
