//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Comprobante_tipo_estado
    {
        public tb_Comprobante_tipo_estado()
        {
            this.tb_Comprobante = new HashSet<tb_Comprobante>();
        }
    
        public string IdEstado_cbte { get; set; }
        public string descripcion_estado { get; set; }
    
        public virtual ICollection<tb_Comprobante> tb_Comprobante { get; set; }
    }
}
