//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Empresa
    {
        public tb_Empresa()
        {
            this.mail_Cuentas_Correo_x_Empresa = new HashSet<mail_Cuentas_Correo_x_Empresa>();
            this.seg_menu_x_tb_empresa = new HashSet<seg_menu_x_tb_empresa>();
            this.seg_menu_x_tb_empresa_x_seg_usuario = new HashSet<seg_menu_x_tb_empresa_x_seg_usuario>();
            this.seg_usuario_x_tb_empresa = new HashSet<seg_usuario_x_tb_empresa>();
            this.tb_Clave_Conting = new HashSet<tb_Clave_Conting>();
            this.tb_Comprobante = new HashSet<tb_Comprobante>();
            this.tb_Sucursal = new HashSet<tb_Sucursal>();
        }
    
        public int IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string RUC { get; set; }
        public string DirMatriz { get; set; }
        public string ContribuyenteEspecial { get; set; }
        public string ObligadoAllevarConta { get; set; }
        public string NombreCertificado { get; set; }
        public string Clave_Certificado { get; set; }
        public Nullable<System.DateTime> FechaValidez { get; set; }
        public bool Estado { get; set; }
        public byte[] logo { get; set; }
        public string Alias { get; set; }
        public string IdToquenAFirmar { get; set; }
        public string cod_Ambiente { get; set; }
        public string cod_TipoEmision { get; set; }
        public string url { get; set; }
        public string Tipo_Notificacion_a_cliente { get; set; }
        public string Nemonico_RIDE { get; set; }
        public string Tipo_Base_Exterior { get; set; }
        public string cadena_conexion_Exterior { get; set; }
        public string Cod_Empresa_Para_DB_Ext { get; set; }
        public string Formato_fecha_Base_ext { get; set; }
        public string Formato_hora_Base_ext { get; set; }
        public string Nombre_tabla_Base_ext { get; set; }
        public string IdCatalogo_micro_emp { get; set; }
        public string IdCatalogo_agent_ret { get; set; }
    
        public virtual ICollection<mail_Cuentas_Correo_x_Empresa> mail_Cuentas_Correo_x_Empresa { get; set; }
        public virtual ICollection<seg_menu_x_tb_empresa> seg_menu_x_tb_empresa { get; set; }
        public virtual ICollection<seg_menu_x_tb_empresa_x_seg_usuario> seg_menu_x_tb_empresa_x_seg_usuario { get; set; }
        public virtual ICollection<seg_usuario_x_tb_empresa> seg_usuario_x_tb_empresa { get; set; }
        public virtual ICollection<tb_Clave_Conting> tb_Clave_Conting { get; set; }
        public virtual ICollection<tb_Comprobante> tb_Comprobante { get; set; }
        public virtual ICollection<tb_Sucursal> tb_Sucursal { get; set; }
    }
}
