//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Parametro
    {
        public int IdParametro { get; set; }
        public string url_ws_sri_Recep_cbte_Prueba { get; set; }
        public string url_ws_sri_Recep_cbte_Produc { get; set; }
        public string url_ws_sri_Autorizacion_cbte_Prueba { get; set; }
        public string url_ws_sri_Autorizacion_cbte_Produc { get; set; }
        public string url_ws_firma_efirm { get; set; }
        public Nullable<bool> Usa_Proxy { get; set; }
        public string Url_Proxy { get; set; }
        public Nullable<int> Port_Proxy { get; set; }
        public string Usuario_Proxy { get; set; }
        public string Password_Proxy { get; set; }
        public Nullable<bool> Registra_Log { get; set; }
        public Nullable<decimal> Version { get; set; }
        public Nullable<int> offline_online { get; set; }
    }
}
