//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sucursal
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string DirEstablecimiento { get; set; }
        public string Establecimiento { get; set; }
        public string PtoEmision { get; set; }
        public string Secuencial { get; set; }
        public bool Estado { get; set; }
    
        public virtual tb_Empresa tb_Empresa { get; set; }
    }
}
