//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Tocken
    {
        public string IdTocken { get; set; }
        public string nom_tocken { get; set; }
        public string Password { get; set; }
        public string Serie { get; set; }
        public string Modelo { get; set; }
        public string IdTipo { get; set; }
        public string Estado { get; set; }
    }
}
