//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Comprobante_Tipo
    {
        public int IdEmpresa { get; set; }
        public string descripcion_tipo { get; set; }
        public string cod_tipo { get; set; }
        public byte[] File_disenio_rpt { get; set; }
        public string IdComprobante_tipo { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
    }
}
