//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mail_Cuentas_Correo_x_mail_Mensaje_Tipo
    {
        public string Id { get; set; }
        public string IdCuenta { get; set; }
        public string Nombre_cuenta { get; set; }
        public string direccion_correo { get; set; }
        public string IdTipo_mensaje { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> orden { get; set; }
        public string estado { get; set; }
    }
}
