//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwseg_menu_x_tb_empresa_x_seg_usuario
    {
        public int IdEmpresa { get; set; }
        public int IdMenu { get; set; }
        public string IdUsuario { get; set; }
        public bool nuevo { get; set; }
        public bool modificar { get; set; }
        public bool consultar { get; set; }
        public bool anular { get; set; }
    }
}
