//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwseg_usuario_x_tb_empresa
    {
        public int IdEmpresa { get; set; }
        public string IdUsuario { get; set; }
        public string RazonSocial { get; set; }
        public string us_contrasenia { get; set; }
        public string us_nombre { get; set; }
    }
}
