//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_Comprobante_para_exportar
    {
        public int IdEmpresa { get; set; }
        public string IdComprobante { get; set; }
        public string IdTipoDocumento { get; set; }
        public string IdEstado_cbte { get; set; }
        public string Cedula_Ruc { get; set; }
        public string Numero_Autorizacion { get; set; }
        public string RutaArchivo { get; set; }
        public string Nombre_file { get; set; }
        public Nullable<System.DateTime> Fecha_Emi_Fact { get; set; }
        public Nullable<System.DateTime> Fecha_transaccion { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public string ClaveContingencia { get; set; }
        public string Ambiente { get; set; }
        public string Clave_Acceso { get; set; }
        public string EstadoDoc { get; set; }
        public Nullable<System.DateTime> fecha_hora_exportacion { get; set; }
        public string Nom_emisor { get; set; }
        public string Tipo_Base_Exterior { get; set; }
        public string cadena_conexion_Exterior { get; set; }
        public string Cod_Empresa_Para_DB_Ext { get; set; }
        public string Nom_Contribuyente { get; set; }
    }
}
