//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Info.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirmElect.Info.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2012 sp1 (x64) (http://www.altova.com) by Jacobo Salazar (Particular) --&gt;
        ///&lt;!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by ALEJANDRO SUBIA (SERVICIO DE RENTAS INTERNAS) --&gt;
        ///&lt;xsd:schema xmlns:ns1=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xsd:simpleType name=&quot;numeroRuc&quot;&gt;
        ///		&lt;xsd:annotation&gt;
        ///			&lt;xsd:documentation&gt;Se detalla el numero de RUC del Contribuyente&lt;/xsd:documentation&gt;
        ///		&lt;/xsd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string comprobanteRetencion {
            get {
                return ResourceManager.GetString("comprobanteRetencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xsd:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot;
        ///		schemaLocation=&quot;xmldsig-core-schema.xsd&quot;/&gt;
        ///	&lt;xsd:simpleType name=&quot;ambiente&quot;&gt;
        ///		&lt;xsd:annotation&gt;
        ///			&lt;xsd:documentation&gt;Desarrollo o produccion depende de en cual ambiente se genere el comprobante.&lt;/xsd:documentation&gt;
        ///		&lt;/xsd:annotation&gt;
        ///		&lt;xsd:restriction base=&quot;xsd:string&quot;&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Factura_V_2_1_0 {
            get {
                return ResourceManager.GetString("Factura_V_2_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by ALEJANDRO SUBIA (SERVICIO DE RENTAS INTERNAS) --&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:ns1=&quot;http://www.w3.org/2000/09/xmldsig#&quot; elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xsd:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot;
        ///		schemaLocation=&quot;xmldsig-core-schema.xsd&quot;/&gt;
        ///	&lt;xsd:simpleType name=&quot;numeroRuc&quot;&gt;
        ///		&lt;xsd:annotation&gt;
        ///			&lt;xsd:documentati [rest of string was truncated]&quot;;.
        /// </summary>
        public static string guiaRemision {
            get {
                return ResourceManager.GetString("guiaRemision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xsd:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot;
        ///		schemaLocation=&quot;xmldsig-core-schema.xsd&quot;/&gt;
        ///	&lt;xsd:simpleType name=&quot;ambiente&quot;&gt;
        ///		&lt;xsd:annotation&gt;
        ///			&lt;xsd:documentation&gt;Desarrollo o produccion depende de en cual ambiente se genere el comprobante.&lt;/xsd:documentation&gt;
        ///		&lt;/xsd:annotation&gt;
        ///		&lt;xsd:restriction base=&quot;xsd:s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Liquidacion_Compra_V_1_1_0 {
            get {
                return ResourceManager.GetString("Liquidacion_Compra_V_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by ALEJANDRO SUBIA (SERVICIO DE RENTAS INTERNAS) --&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xsd:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot;
        ///		schemaLocation=&quot;xmldsig-core-schema.xsd&quot;/&gt;
        ///	&lt;xsd:simpleType name=&quot;numeroRuc&quot;&gt;
        ///		&lt;xsd:annotation&gt;
        ///			&lt;xsd:documentation&gt;Se detalla el numero de RUC del Con [rest of string was truncated]&quot;;.
        /// </summary>
        public static string notaCredito {
            get {
                return ResourceManager.GetString("notaCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2012 sp1 (x64) (http://www.altova.com) by Jacobo Salazar (Particular) --&gt;
        ///&lt;!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by ALEJANDRO SUBIA (SERVICIO DE RENTAS INTERNAS) --&gt;
        ///&lt;xsd:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xsd:simpleType name=&quot;numeroRuc&quot;&gt;
        ///		&lt;xsd:annotation&gt;
        ///			&lt;xsd:documentation&gt;Se detalla el numero de RUC del Contribuyent [rest of string was truncated]&quot;;.
        /// </summary>
        public static string notaDebito {
            get {
                return ResourceManager.GetString("notaDebito", resourceCulture);
            }
        }
    }
}
